import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Button, ButtonGroup } from '@chakra-ui/react'
import { Flex, Spacer } from '@chakra-ui/react'
import { Center, Square, Circle } from '@chakra-ui/react'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <body>
      <Flex as="nav" justifyContent={'space-between'} py={4} px={3}>
      <a href=""><img src={"/images/logo.svg"} width="150px" /></a>

      <Button colorScheme='blue' bg="green.500">Reports</Button>
      </Flex>

      <Center class="hero" h='100px' fontSize={50} fontWeight={700}>
      Report environmental challenges, make Niger Delta better
    </Center>
    </body>
      
    </div>
  )
}
